<a href="https://colab.research.google.com/github/Orpita3/Deliverable-4---Arrays/blob/master/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#@title Default title text
# Step (1): Importing libraries
import pandas as pd
import numpy as np
import seaborn as sns

iris = sns.load_dataset('iris')
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
iris.drop(iris.columns[4], axis=1, inplace=True)

In [5]:
iris.head()

NameError: ignored

In [ ]:
iris = iris.assign(sepal_sum = lambda x: x.sepal_length + x.sepal_width)
iris = iris.assign(petal_sum = lambda x: x.petal_length + x.petal_width)

In [ ]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width  sepal_sum  petal_sum
0           5.1          3.5           1.4          0.2        8.6        1.6
1           4.9          3.0           1.4          0.2        7.9        1.6
2           4.7          3.2           1.3          0.2        7.9        1.5
3           4.6          3.1           1.5          0.2        7.7        1.7
4           5.0          3.6           1.4          0.2        8.6        1.6

In [3]:
data = {'avg': [], 'stddev': [], 'minm': [], 'maxm': []}
index = []
for col in iris.columns:
    index.append(col)
    data['avg'].append(round(iris[col].mean(),6))
    data['stddev'].append(round(iris[col].std(),6))
    data['minm'].append(round(iris[col].min(),6))
    data['maxm'].append(round(iris[col].max(),6))


index.insert(2,index[-2])
index.pop(-2)

for key in data:
    data[key].insert(2,data[key][-2])
    data[key].pop(-2)

new_df = pd.DataFrame(data, index)

NameError: ignored

In [ ]:
new_df.head()

               average  stdeviation  minimum  maximum
sepal_length  5.843333     0.828066      4.3      7.9
sepal_width   3.057333     0.435866      2.0      4.4
sepal_sum     8.900667     0.889272      6.8     11.7
petal_length  3.758000     1.765298      1.0      6.9
petal_width   1.199333     0.762238      0.1      2.5